config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  
  devise_for :users, controllers: { registrations: 'registrations' }
  
  devise_scope :user do
    get 'users', :to => 'registrations#show', :as => :user
  end
  
  get 'search', to:"home#search"
  
  authenticate :user do
    resources :vacancies, only: %i[new create edit update destroy]
    resources :companies, only: %i[new create show]
    resources :candidatures, only: %i[create show]
    get 'user_candidature/:user_id', :to => 'candidatures#users_show', as: 'user_candidature'
    resources :candidature_approvals, only: %i[create show] do
      post 'accept', on: :member
      post 'reject', on: :member
    end
    get 'new/approval/:candidature_id', :to => 'candidature_approvals#new', as: 'new_candidature_approvals' do
    end
    resources :candidature_denials, only: %i[create show]
    get 'new/denial/:candidature_id', :to => 'candidature_denials#new', as: 'new_candidature_denials'

  end

  resources :vacancies, only: %i[index show]

end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  validates :role, :description, :requirements, :localization, :expiration_date, presence: true

  enum status: { active: 0, inactive: 5 }

  def self.visitor_valid_vacancies
    Vacancy.where(' status = ? AND expiration_date >= ?', 0, Time.zone.today)
  end

  belongs_to :company
  has_many :candidature

  Vacancy.joins(:company)
  Vacancy.joins(:candidature)
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  def index
    @vacancies = Vacancy.visitor_valid_vacancies
    @user = User.find(current_user.id) if user_signed_in?
  end

  def show
    @visible = true
    @vacancy = Vacancy.find(params[:id])
    if user_signed_in?
      @user = User.find(current_user.id)
      @visible = false if @user.company_id == @vacancy.company_id
    end
  end

  def new
    @vacancy = Vacancy.new
    user = User.find(current_user.id)

    if user.cpf.nil?
      redirect_to edit_user_registration_path(current_user.id)
      flash[:notice] = 'Necessário preencher o perfil e
                        cadastrar empresa antes de criar nova vaga.'
    end
  end

  def create
    vacancy_params = params.require(:vacancy).permit(:role, :description,
                                                     :requirements, :localization, :expiration_date)
    @vacancy = Vacancy.new(vacancy_params)
    user = User.find(current_user.id)
    @vacancy.company_id = user.company_id

    if @vacancy.save
      redirect_to @vacancy
    else
      render 'new'
    end
  end

  def edit
    @vacancy = Vacancy.find(params[:id])
  end

  def update
    @vacancy = Vacancy.find(params[:id])

    vacancy_params = params.require(:vacancy).permit(:role, :description,
                                                     :requirements, :localization, :expiration_date)

    if @vacancy.update(vacancy_params)
      redirect_to @vacancy
    else
      render :edit
    end
  end

  def destroy
    @vacancy = Vacancy.find(params[:id])
    @vacancy.destroy

    redirect_to @vacancy, :notice => 'Vaga deletada com sucesso!'
  end
end

app/views/vacancies/edit.html.erb
<%= link_to 'Voltar', vacancy_path %>

<h2>Editar Vaga <%= @vacancy.company.company_name %></h2>

<% if @vacancy.errors.any? %>
  <div class="alert">
    <p>Não foi possível editar a vaga</p>
    <p>Veja erros abaixo:</p>
    <ul>
    <% @vacancy.errors.full_messages.each do |v| %>
      <li><%= v %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'partials/vacancies/form' %>

app/views/vacancies/index.html.erb
<% if @vacancies.empty? %>
  <div class='warning'>Nenhuma vaga cadastrada!</div>
<% else %>
  <% @vacancies.each do |vacancy| %>
    <dl>
      <dt><h4>Empresa</h4></dt>
      <dd><%= link_to vacancy.company.company_name, vacancy %></dd>
      <dt><h4>Cargo</h4></dt>
      <dd><%= vacancy.role %></dd>
      <% if user_signed_in? && @user.Admin? %> 
        <dd>Número de candidaturas: <%= vacancy.candidature.count %></dd>
      <% end %>
    </dl>
    <hr>
    
</dl>  
  <% end %>
<% end %>

<% if user_signed_in? && @user.company_id.nil? == false && @user.Admin? %>
  <%= link_to 'Cadastrar nova vaga', new_vacancy_path %>
<% end %>
<%= link_to 'Voltar', root_path%>

app/views/vacancies/new.html.erb
<h1>Nova Vaga</h1>
<%= render 'partials/error_alert', resource: @vacancy %>

<%= render 'partials/vacancies/form' %>

app/views/vacancies/show.html.erb
<% if user_signed_in? && @user.company_id.nil? == false && @user.Admin? %>
  <ul>
        <li><%= link_to 'Editar', edit_vacancy_path(@vacancy) %></li>
        <li><%= link_to 'Deletar', vacancy_path(@vacancy), method: :delete, data: { confirm: "Tem certeza que deseja deletar a vaga?" } %></li>
  </ul>
<% end %>

<h1>Vaga de <%= @vacancy.role %> em <%= @vacancy.company.company_name %></h1>

<dl>
  <dt><h4>Descrição</h4></dt>
  <dd><%= @vacancy.description %></dd>
  <dt><h4>Requisitos</h4></dt>
  <dd><%= @vacancy.requirements %></dd>
  <dt><h4>Localização</h4></dt>
  <dd><%= @vacancy.localization %></dd>
  <dt><h4>Data de Expiração</h4></dt> 
  <dd><%= I18n.localize @vacancy.expiration_date %></dd>
  
  <% if @visible %>
    <%= form_with model: @candidature, url: candidatures_path  do |f| %>
        <%= f.hidden_field :vacancy_id, value: @vacancy.id %>
        <%= f.submit 'Candidatar' %>
    <% end %>
  <% end %>


  <% if user_signed_in? %>  
    <% unless @user.company_id.nil? %>
      <%= link_to 'Candidaturas', candidature_path(@vacancy.id) %></dd>
    <% end %>
  <% end %>
  <%= link_to 'Voltar', vacancies_path %>
</dl>