config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  
  devise_for :users, controllers: { registrations: 'registrations' }
  
  devise_scope :user do
    get 'users', :to => 'registrations#show', :as => :user
  end
  
  get 'search', to:"home#search"
  
  authenticate :user do
    resources :vacancies, only: %i[new create edit update destroy]
    resources :companies, only: %i[new create show]
    resources :candidatures, only: %i[create show]
    get 'user_candidature/:user_id', :to => 'candidatures#users_show', as: 'user_candidature'
    resources :candidature_approvals, only: %i[create show] do
      post 'accept', on: :member
      post 'reject', on: :member
    end
    get 'new/approval/:candidature_id', :to => 'candidature_approvals#new', as: 'new_candidature_approvals' do
    end
    resources :candidature_denials, only: %i[create show]
    get 'new/denial/:candidature_id', :to => 'candidature_denials#new', as: 'new_candidature_denials'

  end

  resources :vacancies, only: %i[index show]

end

app/models/candidature.rb
class Candidature < ApplicationRecord
  belongs_to :vacancy
  belongs_to :user

  enum status: { pendent: 0, approved: 5, denied: 10 }

  Candidature.joins(:vacancy)
  Candidature.joins(:user)
end

app/controllers/candidatures_controller.rb
class CandidaturesController < ApplicationController
  def create
    @candidature = Candidature.new
    @candidature.vacancy_id = params[:vacancy_id]
    @candidature.user_id = current_user.id
    user = User.find(current_user.id)

    if user.cpf.nil?
      flash[:notice] = 'Necessário preencher perfil para se cadastrar a vagas.'
      redirect_to vacancy_path(params[:vacancy_id])
    else
      @candidature.save
      flash[:notice] = 'Candidatura registrada com sucesso!'
      redirect_to vacancy_path(params[:vacancy_id])
    end
  end

  def show
    @vacancy_id = params[:id]
    @candidature = Candidature.where(' vacancy_id = ?', @vacancy_id)
  end

  def users_show
    @candidature = Candidature.where(' user_id = ?', params[:user_id])
  end
end

app/views/candidatures/show.html.erb
<h1>Candidaturas</h1>

<% if @candidature.empty? %>
  <td>Nenhuma candidatura recebida até o momento.</td>
  <br>
  <br>
<% else %>
  <% @candidature.each do |c| %>
    <table>
      <tr>
        <td><b>Nome completo:</b></td>
        <td><%= c.user.complete_name %></td>
      </tr>
      <tr>
        <td><b>CPF:</b></td>
        <td><%= c.user.cpf %></td>
      </tr>
      <tr>
        <td><b>Telefone:</b></td>
        <td><%= c.user.phone_number %></td>
      </tr>
      <tr>
        <td><b>Biografia:</b></td>
        <td><%= c.user.phone_number %></td>
      </tr>

      <% if c.status == 'pendent' %>
        <tr>
          <td><%= link_to 'Aceitar candidatura', new_candidature_approvals_path(c.id) %></td>
          <td><%= link_to 'Recusar candidatura', new_candidature_denials_path(c.id) %></td>
        </tr>
      <% else %>
        <tr>
          <td><b>Status:</b></td>
          <td><%= c.status %></td>
        </tr>
      <% end %>
    </table>
    
    
    <hr>
  <% end %>
<% end %>

<%= link_to 'Voltar', vacancy_path(@vacancy_id) %>

app/views/candidatures/users_show.html.erb
<h1>Lista de candidaturas</h1>

<% @candidature.each do |c| %>
    <table>
      <tr>
        <td><b>Empresa</b></td>
        <td><%= c.vacancy.company.company_name %></td>
      </tr>
      <tr>
        <td><b>Cargo:</b></td>
        <td><%= c.vacancy.role %></td>
      </tr>
      <tr>
        <td><b>Status:</b></td>
        <td><%= c.status %></td>
      </tr>
    </table>
      <% if c.status == 'approved' %>
        <%= link_to 'Ver proposta', candidature_approval_path(c.id) %>
      <% elsif c.status == 'denied' %>
        <%= link_to 'Ver feedback', candidature_denial_path(c.id) %>
      <% end %>
    <hr>
<% end %>

<%= link_to 'Voltar', root_path %>