config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  
  devise_for :users, controllers: { registrations: 'registrations' }
  
  devise_scope :user do
    get 'users', :to => 'registrations#show', :as => :user
  end
  
  get 'search', to:"home#search"
  
  authenticate :user do
    resources :vacancies, only: %i[new create edit update destroy]
    resources :companies, only: %i[new create show]
    resources :candidatures, only: %i[create show]
    get 'user_candidature/:user_id', :to => 'candidatures#users_show', as: 'user_candidature'
    resources :candidature_approvals, only: %i[create show] do
      post 'accept', on: :member
      post 'reject', on: :member
    end
    get 'new/approval/:candidature_id', :to => 'candidature_approvals#new', as: 'new_candidature_approvals' do
    end
    resources :candidature_denials, only: %i[create show]
    get 'new/denial/:candidature_id', :to => 'candidature_denials#new', as: 'new_candidature_denials'

  end

  resources :vacancies, only: %i[index show]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.find(current_user.id) if user_signed_in?
  end

  def search
    @vacancies = Vacancy.joins(:company).where('company_name like ? OR role like ?',
                                               "%#{params[:q]}%", "%#{params[:q]}%")
  end
end

app/views/home/index.html.erb
<% if user_signed_in? %>
    <%= link_to 'Perfil', user_path %>
      <% if @user.company_id.nil? && @user.Admin? %>
          <%= link_to 'Cadastrar empresa', new_company_path%>
      <% elsif @user.company_id.nil? == false && @user.Admin? %>
          <%= link_to 'Informações da empresa', company_path(@user.company_id) %>
      <% end %>
      
      <% if @user.Candidate? %>
          <%= link_to 'Candidaturas', user_candidature_path(@user.id) %>
      <% end %>
<% end %>

<h1>VagasRH</h1>
<h3> Bem vindo ao maior site de vagas de emprego do Brasil! </h3>

<%= form_with url: search_path, method: :get do %>
  <%= label_tag :q, 'Busca:' %>
  <%= text_field_tag :q %>
  <%= submit_tag 'Pesquisar' %>
<% end %>

<%= link_to 'Vagas', vacancies_path%>

app/views/home/search.html.erb
<h1>Resultados da busca</h1>
<ul>
  <% @vacancies.each do |vacancy| %>
    <li><%= link_to vacancy.company.company_name, vacancy %>, <%= vacancy.role %></li>
  <% end %>
</ul>