config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  
  devise_for :users, controllers: { registrations: 'registrations' }
  
  devise_scope :user do
    get 'users', :to => 'registrations#show', :as => :user
  end
  
  get 'search', to:"home#search"
  
  authenticate :user do
    resources :vacancies, only: %i[new create edit update destroy]
    resources :companies, only: %i[new create show]
    resources :candidatures, only: %i[create show]
    get 'user_candidature/:user_id', :to => 'candidatures#users_show', as: 'user_candidature'
    resources :candidature_approvals, only: %i[create show] do
      post 'accept', on: :member
      post 'reject', on: :member
    end
    get 'new/approval/:candidature_id', :to => 'candidature_approvals#new', as: 'new_candidature_approvals' do
    end
    resources :candidature_denials, only: %i[create show]
    get 'new/denial/:candidature_id', :to => 'candidature_denials#new', as: 'new_candidature_denials'

  end

  resources :vacancies, only: %i[index show]

end

app/models/candidature_approval.rb
class CandidatureApproval < ApplicationRecord
  belongs_to :candidature

  validates :salarial_proposal, :start_date, presence: true

  enum offer_response: { pendent: 0, accepted: 5, rejected: 10 }
end

app/controllers/candidature_approvals_controller.rb
class CandidatureApprovalsController < ApplicationController
  def new
    @candidature_approval = CandidatureApproval.new
    @candidature_id = params[:candidature_id]
  end

  def create
    candidature_approval_params = params.require(:candidature_approval).permit(:candidature_id,
                                                                               :salarial_proposal, :start_date)
    @candidature_approval = CandidatureApproval.new(candidature_approval_params)
    @candidature_id = @candidature_approval.candidature_id

    if @candidature_approval.save
      candidature = Candidature.find(@candidature_id)
      candidature.update(status: 5)
      flash[:notice] = 'Proposta enviada com sucesso.'
    end
    render 'new'
  end

  def show
    @candidature_approval = CandidatureApproval.where('candidature_id = ?', params[:id])
  end

  def accept
    @candidature_approval = CandidatureApproval.find(params[:id])
    candidature_id = @candidature_approval.candidature_id
    @candidature_approval.accepted!
    redirect_to candidature_approval_path(candidature_id)
  end

  def reject
    @candidature_approval = CandidatureApproval.find(params[:id])
    candidature_id = @candidature_approval.candidature_id
    @candidature_approval.rejected!
    redirect_to candidature_approval_path(candidature_id)
  end
end

app/views/candidature_approvals/new.html.erb
<h1>Proposta de emprego</h1>

<% if @candidature_approval.errors.any? %>
  <div class="alert">
    <p>Não foi possível enviar a proposta</p>
    <p>Confira os erros abaixo:</p>
    <ul>
      <% @candidature_approval.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end%>

<%= form_with model: @candidature_approval do |f| %>

  <%= f.hidden_field :candidature_id, value: @candidature_id %>

  <div>
    <%= f.label :salarial_proposal %>
    <%= f.text_field :salarial_proposal %>
  </div>
  <div>
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
  </div>

  <%= f.submit 'Enviar proposta' %>
  <br>
<% end %>

<%= link_to 'Voltar', candidature_path(@candidature_id) %>



 

app/views/candidature_approvals/show.html.erb
<h1>Proposta de emprego</h1>

<% @candidature_approval.each do |c| %>
  <table>
    <tr>
      <td><b>Salário</b></td>
      <td><%= c.salarial_proposal %></td>
    </tr>
    <tr>
      <td><b>Data de início</b></td>
      <td><%= c.start_date.strftime('%d/%m/%Y') %></td>
    </tr>
  </table>

  <% if c.offer_response == 'pendent'%>
    <%= link_to 'Aceitar proposta', accept_candidature_approval_path(c.id), method: :post %>
    <%= link_to 'Recusar proposta', reject_candidature_approval_path(c.id), method: :post %>
  <% else %>
    <td><b>Status</b></td>
    <%= c.offer_response %>
  <% end %>
  <br>
  <br>
<% end %>



<%= link_to 'Voltar', user_candidature_path(current_user.id)  %>